site_name: Ny i Norge 🇺🇦
theme:
  font:
    text: Montserrat
  name: material
  palette:
      scheme: default
  language: ru
  logo: assets/norway-icon.svg
  favicon: assets/favicon.png
  features:
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.share
    - navigation.top

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Главная: 'index.md'
  - Коллективная защита: 'collective-protection.md'
  - Интродукционная (ознакомительная) программа: 'introduction-programme.md'
  - Въезд с домашним питомцем в Норвегию: 'animals.md'
  - Водителям: 'automobile.md'
  - Экономическая поддержка: 'benefits.md'
  - Жилье: 'housing.md'
  - Таможенные правила: 'toll.md'
  - Статистика: 'stats.md'
  - Про работу в Норвегии: 'work.md'
  - Иные вопросы: 'other.md'


plugins:
  - redirects:
      redirect_maps:
        'other.md': 'annet.md'
  - search:
      lang: 
        - ru
        - en

markdown_extensions:
- footnotes
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- footnotes
- toc:
      permalink: true
      baselevel: 2
- admonition
- pymdownx.details
- pymdownx.superfences
copyright: Copyright &copy; 2023 Ny i Norge. Слава Україні!
